### PR TITLE
CSS Done!

### PR DESCRIPTION
**Pull request by Timbaron**

### CODE REVIEW

**Review by otilor — COMMENTED** [review]
What of the JS files?

**Comment by Timbaron** [comment]
> 
> 
> What of the JS files?

Pulling shortly,... hang on

**Comment by otilor** [comment]
> 
> 
> > What of the JS files?
> 
> Pulling shortly,... hang on

Ok  man

**Comment by TIMIAK** [comment]
sent

**Review by otilor — APPROVED** [review]
Nice Job!

**Pull request merged**
